#!/bin/sh

if xl info >/dev/null 2>/dev/null ; then
    cores=0-47
    swap="qw(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95)"
else
    cores=0-47
    prehook="modprobe msr"
    posthook="rmmod msr"
    swap="qw(0 4 8 12 16 20 24 28 32 36 40 44 3 7 11 15 19 23 27 31 35 39 43 47 2 6 10 14 18 22 26 30 34 38 42 46 1 5 9 13 17 21 25 29 33 37 41 45 48 52 56 60 64 68 72 76 80 84 88 92 51 55 59 63 67 71 75 79 83 87 91 95 50 54 58 62 66 70 74 78 82 86 90 94 49 53 57 61 65 69 73 77 81 85 89 93)"
fi

case "$1" in
    pre)
        $prehook
	;;
    run)
	exec 1> "$LOGDIR/raw.dat"
	exec rwmsr --core=$cores \
	      0xc0010000=0x00043277d@0-1000  \
	      0xc0010001=0x000430f7e@0-1000  \
	      \
	      :0xc0010004=0@0-1000 \
	      :0xc0010005=0@0-1000
	;;
    post)
        $posthook
	perl -wlan                                       \
	     -e 'BEGIN {                               ' \
	     -e '  printf "time";                      ' \
	     -e '  foreach $core (0..47) {             ' \
	     -e '    printf " 00043277d-%s", $core;    ' \
	     -e '  }                                   ' \
	     -e '  foreach $core (0..47) {             ' \
	     -e '    printf " 000430f7e-%s", $core;    ' \
	     -e '  }                                   ' \
	     -e '  printf "\n";                        ' \
	     -e '}                                     ' \
	     -e '($. <= 2) and next;                   ' \
	     -e 'printf "%s ", shift(@F);              ' \
	     -e '@F = map { $F[$_] }                   ' \
	     -e "     $swap;                           " \
	     -e 'print join(" ", @F);                  ' \
	     "$LOGDIR/raw.dat"                           \
	     > "$LOGDIR/l2load.dat"
	rm "$LOGDIR/raw.dat"
	;;
    *)
	exit 1
	;;
esac
