#!/bin/sh


case "$1" in
    pre)
	xen-trigger -12
	;;
    post)
	xen-trigger -13
	;;
    run)
	exec  >"${LOGDIR}/xen-carrefour-out.log"
	exec 2>"${LOGDIR}/xen-carrefour-err.log"
	exec xen-carrefour
	;;
    *)
	exit 1
	;;
esac
