#!/bin/sh


case "$1" in
    pre)
	for p in `perl -wnl -e '/^processor\s+:\s+(\d+)/ and print $1' \
                      /proc/cpuinfo` ; do
	    xl vcpu-pin 0 $p $p
	done
	xen-trigger -12
	;;
    post)
	xen-trigger -13
	;;
    run)
	exec  >"${LOGDIR}/xen-carrefour-out.log"
	exec 2>"${LOGDIR}/xen-carrefour-err.log"
	exec xen-carrefour
	;;
    *)
	exit 1
	;;
esac
