#!/bin/sh

cache="private/cache"
cache_param="${cache}/param"
cache_disk="${cache}/disk"
err=0

if [ -e "${cache}" ] ; then
    rm -rf "${cache}"
fi

mkdir "${cache}"
mkdir "${cache_param}"
mkdir "${cache_disk}"


./method/_fill_cache            \
  && ./method/_prepare_config   \
  && ./method/_prepare_image    \
  || err=1


exit $err
