#!/bin/sh

# Getting the self root

self="${0%method/*}"


# Permission checking

if [ `whoami` != "root" ] ; then
    echo "$0: you must be root" >&2
    exit 1
fi


ssh -o ControlMaster=no -o ControlPath="${self}/private/ssh-control.sock" \
    `cat "${self}/private/cache/param/ip"` "$@"
