all:
	make all -C activecond
	make all -C busyloop
	make all -C chronometer
	make all -C pin
	make all -C rusage

clean:
	make clean -C activecond
	make clean -C busyloop
	make clean -C chronometer
	make clean -C pin
	make clean -C rusage

