all: pin
	make all -C activecond
	make all -C busyloop
	make all -C chronometer
	make all -C rusage

clean:
	make clean -C activecond
	make clean -C busyloop
	make clean -C chronometer
	make clean -C rusage
